version: '3.2'

services:
  influxdb:
    env_file: configuration.env
    build: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    env_file: configuration.env
    build: grafana
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}
